# remap from C-b to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# colours, source, and list windows starting with 1
set -g status-style 'bg=#333333 fg=#5eacd3'
set -ga terminal-overrides ",xterm-256color*:Tc"
bind r source-file ~/.config/tmux/tmux.conf
set -g base-index 1

#set-option -g default-terminal "screen-256color"

set-option -g focus-events on
set-option -sg escape-time 10

# change the maximum length of session names and other stuff to 50 chars
set -g status-left-length 50
set -g status-right-length 120
set -g status-right "#(tmux-mem-cpu-load --interval 1 --averages-count 0)"
set -g status-interval 2

# if run as "tmux attach", create a session if one does not already exist
new-session -n $HOST -s get-this-bread

# split panes with - and |
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind-key -r i run-shell "tmux neww ~/.dotfiles/cht.sh"

bind - split-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

